# Takes a repository with mnkdocs source, generates the static site and
# pushes the result to Codeberg pages
#
# Needs a codeberg access token (codeberg_token) as a secret in
# Woodpecker config Also uses another secret (mail) with email address
# for git config
#
# .domains file in the repository is copied to the output branch so
# custom domains work
#
# this file was copied from
# https://codeberg.org/Codeberg-CI/examples/src/branch/main/Mdbook/.woodpecker.yaml
---
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      # to make the git-revision-date.. plugin work
      partial: false

when:
  branch: ${CI_REPO_DEFAULT_BRANCH}
  event: [push, manual]

steps:
  build:
    image: squidfunk/mkdocs-material
    commands:
      - pip install -r requirements.txt
      - mkdocs build
      - git fetch --all
      - git worktree add ../fr/ fr
      - cd ../fr && mkdocs build -d site/fr

  # this is still the legacy v2 pages systm
  #
  # see the README file for a discussion
  publish:
    image: alpine/git
    environment:
      OUTPUT_DIR: site
      # secrets must be set in Woodpecker configuration
      MAIL:
        from_secret: mail
      CODEBERG_TOKEN:
        from_secret: codeberg_token
    commands:
      - apk add rsync
      - git config --global user.email $MAIL
      - git config --global user.name "Woodpecker CI"
      - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git $CI_REPO_NAME
      - rsync --delete --recursive --checksum --exclude '.git/**' $OUTPUT_DIR/. $CI_REPO_NAME/
      - cp .domains $CI_REPO_NAME || true
      - cd $CI_REPO_NAME
      - git add .
      - if ! git diff --cached --quiet; then git commit -m "Woodpecker CI ${CI_BUILD_CREATED}" && git push; fi

  aspell:
    image: debian
    commands:
      - ./spellcheck.sh en
      - cd ../fr && ./spellcheck.sh fr

  checklinks:
    image: containers.torproject.org/tpo/web/container-images/lychee
    environment:
      OUTPUT_DIR: site
      # secrets must be set in Woodpecker configuration
      MAIL:
        from_secret: mail
      CODEBERG_TOKEN:
        from_secret: codeberg_token
    commands:
      - apt-get update && apt-get install -y git
      - git config --global user.email $MAIL
      - git config --global user.name "Woodpecker CI"
      # cache using git while we wait for a woodpecker cache, see the
      # README for a discussion
      - git clone -b cache https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git cache
      # we *must* go in the cache directory because we can't relocate
      # the lychee cache, see:
      # https://github.com/lycheeverse/lychee/issues/1700
      - cp .lycheeignore cache
      - cd cache
      - lychee ../site --root-dir ../site/ --include-fragments --index-files index.html --no-progress --cache --cache-exclude-status "401,429,500.." --max-cache-age 30d --scheme http --scheme https --require-https
      - sort .lycheecache > .lycheecache.sorted && mv .lycheecache.sorted .lycheecache
      - git add .
      - if ! git diff --cached --quiet; then git commit -m "Woodpecker CI cache update ${CI_BUILD_CREATED}" && git push; fi

