---
site_name: Réseau Libre
site_url: https://lora.reseaulibre.ca
site_description: Mesh networking experiments in Montréal
site_author: Anarcat and others
copyright: Copyleft &copy; CC-BY-SA 4.0
repo_url: https://codeberg.org/reseaulibre/lora-reseaulibre-ca
edit_uri: _edit/main/docs/
nav:
  - About:
    - index.md
    - values.md
    - history.md
    - Contact: contact.md
    - FAQ: guides/faq.md
    - Code of Conduct: code.md
  - Guides:
    - guides/index.md
    - MeshCore:
      - guides/meshcore/index.md
      - guides/meshcore/companion.md
      - guides/meshcore/channels.md
      - guides/meshcore/repeater.md
      - guides/meshcore/upgrades.md
    - Reticulum:
      - guides/reticulum/index.md
      - guides/reticulum/rns.md
      - guides/reticulum/lxmf-cli.md
      - guides/reticulum/meshcore.md
      - guides/reticulum/rtnode.md
    - Meshtastic: guides/meshtastic.md
    - guides/net.md
    - Matrix: guides/matrix.md
    - FAQ: guides/faq.md
  - References:
    - references/index.md
    - Hardware:
        - references/hardware/index.md
        - references/hardware/antennas.md
        - references/hardware/batteries.md
        - references/hardware/power.md
    - Software:
        - references/software/index.md
        - references/software/meshtastic.md
        - references/software/bots.md
        - references/maps.md
        - Meta: meta.md
    - Nodes:
      - references/nodes/index.md
      - references/nodes/*.md
    - references/neighbours.md
    - references/log.md
    - references/other.md
  - News: news/index.md
markdown_extensions:
  # <abbr> tags, with say, *[HTML]: Hyper text...
  - abbr
  # !!! admonitions, deprecated in favor of "github callouts" below
  - admonition
  # attribute lists to blocks, used for buttons, tooltips, image
  # alignment, grids, etc
  - attr_list
  # definition lists, i.e. foo\n: bar
  - def_list
  # [^1]: ...
  - footnotes
  # allow markdown inside HTML, useful for grids, image captions, etc
  - md_in_html
  # support "this is a list\n1. list..."
  #- mdx_breakless_lists
  # allow for sublists with only two indents, workaround upstream bug:
  # https://github.com/zensical/zensical/issues/453
  # actually buggy when actually using 4 spaces lists
  #- mdx_truly_sane_lists:
  #    nested_indent: 2
  #    truly_sane: true
  # tables support
  - tables
  # generate table of contents, with a permalink button next to
  # titles
  - toc:
      permalink: true
  # improve emphasis handling, more in line with commonmark:
  # https://facelessuser.github.io/pymdown-extensions/extensions/betterem/
  - pymdownx.betterem:
      smart_enable: all
  # underline/superscript with ^
  - pymdownx.caret
  # collapsible admonitions
  - pymdownx.details
  # support for :emojis:
  # https://facelessuser.github.io/pymdown-extensions/extensions/emoji/#default-emoji-indexes-twemoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # syntax highlighting for code blocks
  - pymdownx.highlight
  # same, but for `inline` code
  - pymdownx.inlinehilite
  # keyboard keys rendering with ++
  - pymdownx.keys
  # TODO: hot links like #1234
  # https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/#custom-repository-hosts
  #- pymdownx.magiclink
  # highlight with ==
  - pymdownx.mark
  # make admonitions using a more standard blockquote
  #
  # this is actually cargo-culted from Zensical, material for mkdocs
  # doesn't explicitly support this, but it works! 
  - pymdownx.quotes:
      callouts: true
  # turn (c) into ©, disabled: just use unicode directly
  # - pymdownx.smartsymbols
  # include other files, glossary
  # - pymdownx.snippets
  # required for annotations
  - pymdownx.superfences
  # tabs support, alternate style uses less javascript
  - pymdownx.tabbed:
      alternate_style: true
  # improved tab IDs, maybe not necesary
  #    slugify: !!python/object/apply:pymdownx.slugs.slugify
  #      kwds:
  #        case: lower
  # tasks lists with - [ ]
  - pymdownx.tasklist:
      custom_checkbox: true
  # strikethrough with ~~
  - pymdownx.tilde
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/logo.svg
  # disable the roboto font download from google
  font: false
  # the site is in english
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    # - announce.dismiss
    - content.action.edit  # Edit this page
    # broken, it points to _raw, it's raw in codeberg
    # - content.action.view  # View source of this page
    # show footnotes as tooltips
    - content.footnote.tooltips
    # link all content tabs together across all pages
    # allows, for example, for a user to pick a OS in samples and
    # stick to it across the site
    # - content.tabs.link
    # make fancier tooltips on mouseover
    # - content.tooltips
    # hide header when moving past
    # - header.autohide
    # expand navigation by default
    # - navigation.expand
    # prev/next link location
    - navigation.footer
    # allow index.md pages as section indexes
    - navigation.indexes
    # behave as a single page app
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # use top tabs for navigation
    - navigation.tabs
    # make tabs stick to the viewport
    - navigation.tabs.sticky
    # back to top buttons
    - navigation.top
    # update URL bar with current section anchor
    # - navigation.tracking
    # breadcrubs
    - navigation.path
    # prune other sections from the HTML
    # - navigation.prune
    # make top-level sections "groups", degrades back to normal on
    # mobile
    # - navigation.sections
    # highligh matching search results in page
    # - search.highlight
    # allow deeplinks to search results, with a share button
    # - search.share
    # scroll sidebar to match position in table of contents
    # - toc.follow
    # merge table of contents with navigation
    # - toc.integrate

# i thought this would help in translating it all, but it's not the
# way: those are just fixed links.
#
# in mkdocs, this is done with the mkdocs-static-i18n plugin:
# https://ultrabug.github.io/mkdocs-static-i18n/
#
# in zensical, this is the first issue in the backlog:
# https://github.com/zensical/backlog/issues/1
#
# it's blocked by the second one, the design of the module system:
# https://github.com/zensical/backlog/issues/41
extra:
  social:
    - icon: simple/matrix
      link: https://matrix.to/#/#reseaulibre-space:matrix.org
      name: Matrix chat
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.radio/@reseaulibre
      name: Mastodon
    - icon: simple/codeberg
      link: https://codeberg.org/reseaulibre/lora-reseaulibre-ca
      name: Source code
    - icon: material/feather
      link: https://grebedoc.dev
      name: Hosted on grebedoc
  alternate:
    - name: English
      link: /
      lang: en
    - name: Français
      link: /fr/
      lang: fr
plugins:
  # cross-reference across pages
  # - autorefs
  # move navigation to .nav.yml, more flexible than builtin
  # we use literate-nav which is similar
  # - awesome-nav
  # blog posts
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
  # note that the blog plugin is incompatible with the i18n one, see:
  # https://github.com/ultrabug/mkdocs-static-i18n/issues/283
  # https://github.com/squidfunk/mkdocs-material/issues/4863
  - blog:
      blog_dir: news
      categories_allowed:
        - events
        - announcements
  # show page authors at the bottom
  # disabled because for now we only have a single author
  # - git-authors
  # show git modification date, requires mkdocs-git-revision-date-localized-plugin
  # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
  - git-revision-date-localized:
      type: iso_datetime
      enable_creation_date: true
  # for photo galleries?
  # - glightbox
  # mostly to allow wildcards in navigation
  - literate-nav:
      nav_file: SUMMARY.md
  # per-directory .meta.yml file
  # - meta
  # minify and optimize plugins have no effect
  # make the site work offline
  # breaks "nice" links like /3byte/
  #- offline
  # download remote assets and serve localy
  # - privacy
  # build an RSS feed, requires mkdocs-rss-plugin
  - rss:
      match_path: news/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  # set some redirects, requires mkdocs-redirects
  - redirects:
      redirect_maps:
        # can't redirect to blog/category/events/index.md, as
        # redirects thinks it doesn't exist, boooouuuh.
        'events.md': 'news/index.md'
        'blog/index.md': 'news/index.md'
        # the hardware page is really a reference more than a guide
        'guides/hardware.md': 'references/hardware/index.md'
        # obscure FAQ URL that came up for less than a day
        'guides/z_faq.md': 'guides/faq.md'
        'references/mmrelay.md': 'guides/matrix.md#bridging-matrix-and-meshtastic'
        'references/net.md': 'guides/net.md'
        # convenience shortcuts
        '3byte.md': 'news/posts/2026-09-18-3-bytes-hash-mode.md'
        'floods.md': 'news/posts/2026-09-20-limit-flood-and-loops.md'
  # search support, client-side javascript blob
  - search
  # social media cards
  # - social:
  #     cards_layout_options:
  #       background_color: "#000000"
  #       logo: docs/assets/icon.jpg
  # page tagging
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # - tags
