---
site_name: Mesh Montréal
site_url: https://lora.reseaulibre.ca
site_description: The Montreal mesh project"
site_author: Anarcat and others
copyright: Copyleft &copy; CC-BY-SA 4.0
repo_url: https://codeberg.org/anarcat/lora-reseaulibre-ca
edit_uri: edit/main/docs/
# nav:
#   - About: index.md
#   - Guides: guides.md
#   - References: references.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  features:
    # - navigation.prune
    # - navigation.sections
    # - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    - content.action.edit  # Edit this page
    - content.action.view  # View source of this page
  # disable the roboto font download from google
  font: false
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: lucide/moon
        name: Switch to system preference
# should we translate everything?
# extra:
#   alternate:
#     - name: English
#       link: /en/
#       lang: en
#     - name: Français
#       link: /fr/
#       lang: fr
# plugins:
#   # make a nice card for social media
#   # requires cairosvg, not worth?
#   - social
#   # a bunch more possible plugins
#   # blog posts
#   # https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
#   - blog
#   # page tagging
#   # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
#   - tags
#   # update dates from git
#   # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-dates
#   # not packaged in Debian
#   # - git-revision-date-localized:
#   #     enable_creation_date: true
