---
on: [push]
jobs:
  publish:
    runs-on: codeberg-tiny
    container:
      image: squidfunk/mkdocs-material
    steps:
      - run: git clone "${REPOSITORY_URL:-${FORGEJO_SERVER_URL}/${FORGEJO_REPOSITORY}.git}" .
      - run: pip install -r requirements.txt
      - run: mkdocs build
      - run: git fetch --all
      - run: git worktree add ../fr/ fr
      - run: cd ../fr && mkdocs build -d $FORGEJO_WORKSPACE/site/fr

      - uses: actions/git-pages@v2
        with:
          site: https://lora.reseaulibre.ca/
          token: ${{ forge.token }}
          source: site/
          server: grebedoc.dev
        continue-on-error: true

      # sync to the pages branch
      #
      # we don't use the "cache" system because a) it's runner
      # specific and b) it uses node
      #
      # we *could* use the artifacts system for this, but we have
      # haven't figured out how to pull artifacts down just yet
      - run: apt update && apt install rsync
      - run: git config --global user.email $MAIL
      - run: git config --global user.name "Codeberg CI"
      - run: git worktree add ../pages pages
      - run: rsync --delete --recursive --checksum --exclude '.git/**' site/ ../pages/
      - run: cp .domains ../pages/ || true
      - run: git -C ../pages/ add .
      - run: if ! git -C ../pages/ diff --cached --quiet; then git ../pages/ commit -m "Codeberg CI pages update" && git ../pages/ push; fi

  linkcheck:
    needs:
      - publish
    runs-on: codeberg-tiny
    container:
      image: containers.torproject.org/tpo/web/container-images/lychee
    steps:
      - run: apt-get update && apt-get install -y git

      - run: git clone -b pages "${REPOSITORY_URL:-${FORGEJO_SERVER_URL}/${FORGEJO_REPOSITORY}.git}" pages/
      - run: git -C pages/ worktree add cache/ cache
      - run: git -C repo/ worktree add repo/ main
      - run: git config --global user.email $MAIL
      - run: git config --global user.name "Codeberg CI"

      - run: cp repo/.lycheeignore cache
      - run: cd cache
      - run: lychee ../site --root-dir ../site/ --include-fragments --index-files index.html --no-progress --cache --cache-exclude-status "401,429,500.." --max-cache-age 30d --scheme http --scheme https --require-https
      - run: sort .lycheecache > .lycheecache.sorted && mv .lycheecache.sorted .lycheecache

      - run: git -C cache/ add .
      - run: if ! git diff -C cache/ --cached --quiet; then git commit -C cache/ -m "Codeberg CI cache update" && git  -C cache/ push; fi
